### ISSUE TITLE
management statistics database backlogged frequently

### ISSUE THREAD

**Issue by jippi** [rabbitmq/rabbitmq-management#187] opened 2016-04-25 08:21 UTC
Hi,

I upgraded my 3 node cluster (16 cores, 20 GB RAM, SSD) from `3.5.7` to `3.6.1` yesterday, and i've started to see this message happening constantly in the management UI

``The management statistics database currently has a queue of 10094 events to process. If this number keeps increasing, so will the memory used by the management plugin.``

It happens both when the cluster is super busy, and when its mostly idle (in terms of IO messages / sec)

The cluster have ~500-750 consumers across equal amount of channels, ~30 exchanges for 85 queues.

Before 3.5.7 i never saw this message (maybe it's new?) but the "side-effects" of it being shown seem to fit with full cluster freeze (also something happening post-upgrade) 

This morning I had to force-restart the cluster to get it unstuck

This is my config from `3.5.7`

```
[
  {
    rabbit,
    [
      {tcp_listeners, [5672]},
      {collect_statistics_interval, 10000},
      {loopback_users, []},
      {hipe_compile, true},
      {cluster_partition_handling, autoheal},
      {vm_memory_high_watermark, 0.8},
      {log_levels, [
        {connection, warning},
        {mirroring, info},
        {federation, info}
      ]}
    ]
  },

  {
    rabbitmq_management,
    [
      {http_log_dir, "/tmp/rabbit-mgmt"}
    ]
  },

  {
    rabbitmq_management_agent,
    [
      {force_fine_statistics, true}
    ]
  }
].
```

which worked perfectly for a year+ 

When I started to see the issue, I changed the config file to be this (`rates_mode = none` + `force_fine_statistics = false`)  - but i still continue to see the error 

```
[
  {
    rabbit,
    [
      {tcp_listeners, [5672]},
      {collect_statistics_interval, 10000},
      {loopback_users, []},
      {hipe_compile, true},
      {cluster_partition_handling, autoheal},
      {vm_memory_high_watermark, 0.8},
      {log_levels, [
        {connection, warning},
        {mirroring, info},
        {federation, info}
      ]}
    ]
  },

  {
    rabbitmq_management,
    [
      {http_log_dir, "/tmp/rabbit-mgmt"},
      {rates_mode, none}
    ]
  },

  {
    rabbitmq_management_agent,
    [
      {force_fine_statistics, false}
    ]
  }
].
```

I'm running erlang `18.3-1` from erlang-solutions on debian wheezy (erlang was also upgraded yesterday, from `18.2` to `18.3-1`)

I can't see to spot anything in my logs that should indicate something is wrong, and google yields no results for the issue.

**Comment by michaelklishin** [comment] 2016-04-25 11:51
Duplicate of #41.

**Closed by michaelklishin** 2016-04-25 11:51 UTC

**Comment by jippi** [comment] 2016-04-25 14:26
Thanks @michaelklishin !
