### ISSUE TITLE
'Get Message(s)' default in 3.7.x is potentially dangerous

### ISSUE THREAD

**Issue by jwhitex** [rabbitmq/rabbitmq-management#543] opened 2018-01-17 17:20 UTC
## Description

Previous to our teams upgrade to rabbit 3.7 the **default** ```'Ack Mode'``` for the ```'Get messages'``` feature on queue instance tab was ```"requeue"```. The default is now ```'Ack message requeue false'```. 

As a heavy user of this feature, the default should be ```'Nack message requeue true'```. This select option is the least destructive and making it the default will help avoid any unnecessary mishaps.

As shown below, the **desired default** keyvalue key is ```'ack_requeue_true'```.

### Change Requested

Please change the **default** dropdown option on the queue overview screen to be ```'Nack message requeue true'```. If you will accept a pr I will gladly produce one.

## MetaData

* RabbitMQ version: 3.7.2
* Erlang version: 20.1.x

* What management UI page was used (if applicable):

```rabbit.corp.miniter.com:15672/#/queues/${VirtualHost}/${QueueName}```

* How the HTTP API requests performed can be reproduced with `curl`:

This may help confirm we are on the same page. The api request for the 'Get Message(s)' button press. The button resides under the 'Get messages' expando row.

```
{
  url: "http://rabbit.corp.miniter.com:15672/api/queues/${VirtualHost}/${QueueName}/get",
  method: "POST",
  body: {
    ackmode : "ack_requeue_true",
    count : "1",
    encoding : "auto",
    name : "${ServiceName}",
    truncate : "50000",
    vhost : "${VirtualHost}"
  }
}
```

**Comment by michaelklishin** [comment] 2018-01-17 17:22
Duplicate of #542.

**Closed by michaelklishin** 2018-01-17 17:22 UTC
