### ISSUE TITLE
Slow increase in management db memory use when rates_mode = basic

### ISSUE THREAD

**Issue by spatula75** [rabbitmq/rabbitmq-management#214] opened 2016-06-02 01:24 UTC
With RMQ 3.6.2, on a system that is fairly close to idle most of the time, we nonetheless see slow, but consistent memory creep from the management DB, but only when rates_mode is basic. Setting it to 'none' seems to eliminate the problem.  The slope of the curve is highly consistent (about 15MB/hr), even if we turn on scripts to try to create lots of channels, messages, etc:

![image](https://cloud.githubusercontent.com/assets/7718879/15730754/4260cdba-2824-11e6-9c5f-ff803476c45c.png)

Most of this space is being used by the management database table:

![image](https://cloud.githubusercontent.com/assets/7718879/15730876/49663702-2825-11e6-84b2-224a6ecc6c62.png)

Management DB configuration for this host (we've adjusted to shorter retention periods):

```
 {rabbitmq_management,
     [{basic,[{305,5},{1860,60},{3900,300}]},
      {cors_allow_origins,[]},
      {cors_max_age,1800},
      {detailed,[{10,5}]},
      {global,[{305,5},{1860,60},{3900,300}]},
      {http_log_dir,none},
      {listener,[{port,15672}]},
      {load_definitions,none},
      {process_stats_gc_timeout,300000},
      {rates_mode,basic},
      {sample_retention_policies,
          [{global,[{605,5},{3660,60},{29400,600},{86400,1800}]},
           {basic,[{605,5},{3600,60}]},
           {detailed,[{10,5}]}]}]},
```

On a different node, which is identically configured except for setting rates_mode=none (and which is actually busier), we don't see the memory creep:

![image](https://cloud.githubusercontent.com/assets/7718879/15730807/ce34f064-2824-11e6-8370-e75d4332945e.png)

Manually forcing an Erlang GC ( `rabbitmqctl eval '[garbage_collect(P) || P <- processes()].'`) has no effect on the memory consumption.

Our workaround is to set rates_mode=none for now.

**Comment by michaelklishin** [comment] 2016-06-02 14:16
@spatula75 ETS tables are not cleaned up by running runtime GC.

Can you enable `rabbitmq_top` and see what processes consume most RAM?
How many connections, channels, and queues does this system have?

**Comment by spatula75** [comment] 2016-06-02 14:49
RAM usage per process isn't too dramatic. Sorry for the screen shots, but that seems the easiest way to keep the formatting intact:

![image](https://cloud.githubusercontent.com/assets/7718879/15749149/44e902a6-2896-11e6-9769-48a4601bc6dd.png)

![image](https://cloud.githubusercontent.com/assets/7718879/15749183/5c4c95f2-2896-11e6-838b-0e236089f1d8.png)

**Comment by michaelklishin** [comment] 2016-06-03 12:57
@spatula75 thank you. On the chart above we see memory growth over the course of 24 or so hours. Default retention policies collect some samples for up to 24 hours. Does the growth level out after that?

Can you try tweaking retention policies to be e.g. 4 hours to compare? Thank you.

**Comment by spatula75** [comment] 2016-06-03 13:00
Our longest retention period is set to just over an hour, and unfortunately the increase we're seeing never really changes, even after 24 hours.

**Comment by michaelklishin** [comment] 2016-06-03 13:04
@spatula75 OK, good to know. I guess we'll add ETS table info to the UI or rabbitmq-top to make investigating such issues easier.

What kind of workload do you run against this node? Is connection, channel, queue, or binding churn relatively high? We are looking for a way to reproduce.

**Comment by spatula75** [comment] 2016-06-03 14:01
The workload is mostly RPC-like, so once a minute a job will kick off, create channels, create consumers, publish a bunch of messages, close the channels used for publishing, and the consumers will await responses. 

On this cluster  in particular, there are many messages which will time out, though we see similar growth on a cluster with fewer timeouts. 

Probably the most notable thing is a somewhat high amount of channel churn. I tried to make the problem worse by writing a script that repeatedly created a huge number of channels and then closed them, but this did not seem to affect the growth rate.

**Comment by michaelklishin** [comment] 2016-06-03 14:04
@spatula75 OK, thanks, that's also helpful. We'll start by introducing https://github.com/rabbitmq/rabbitmq-management/issues/215 and then using it to see if we can trigger unusual table size growth.

**Comment by spatula75** [comment] 2016-06-03 21:12
Cool. If/when you have a build containing #215, I'd be happy to run it on this cluster and point our normal workload at it to see if we can see which table(s) are causing trouble.

**Comment by michaelklishin** [comment] 2016-06-06 19:53
OK, looks like #217 largely addresses it, at least per @gmr's comment his test tool no longer can reproduce the issue even after running for 10 times as long.

We will produce a milestone build for @spatula75 to try. Closing this but feel free to reopen if #217 wasn't sufficient for the workload you have (and please provide a way to reproduce!)

**Closed by michaelklishin** 2016-06-06 19:53 UTC
Labels: bug, need-followup

**Comment by spatula75** [comment] 2016-06-06 19:55
Sounds promising.  We'll evaluate it just as soon as the milestone build is available.

**Comment by gmr** [comment] 2016-06-06 20:21
@spatula75 I included a pre-built drop-in for the plugin on ticket #217 if you wanted to test with that.

**Comment by spatula75** [comment] 2016-06-06 20:28
@gmr thanks, giving it a try now.

**Comment by spatula75** [comment] 2016-06-06 20:53
@gmr: is it expected that this build of the plugin will report many node-specific statistics (eg, memory, IO, descriptors, space) as 0's when it's loaded in 3.6.2?

**Comment by michaelklishin** [comment] 2016-06-06 20:54
@spatula75 most node-wide stats are reported by `rabbitmq_management_agent`, which is a separate plugin. This change cannot affect those stats.

**Comment by spatula75** [comment] 2016-06-06 20:56
Looks like it happens if I select a date range for the graphs that's longer than the available history.  If I choose something like "last minute" then it's fine.  Probably unrelated and not a big deal.

**Comment by spatula75** [comment] 2016-06-06 21:33
So far this looks encouraging.  The management DB has been running for an hour in our environment with no bloat.

**Comment by michaelklishin** [comment] 2016-06-06 23:37
[3.6.3 Milestone 1](https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_3_milestone1) includes this.
