### ISSUE TITLE
Rapid closure of many channels causes mgmt DB RAM use to spike

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#28] opened 2015-03-24 10:45 UTC
See [this mailing list thread](https://groups.google.com/forum/#!topic/rabbitmq-users/nvCFKJ0HWH0).

**Comment by simonmacmullen** [comment] 2015-04-02 10:32
Duplicate of https://github.com/rabbitmq/rabbitmq-server/issues/86

**Closed by simonmacmullen** 2015-04-02 10:32 UTC
Labels: enhancement
