### ISSUE TITLE
Rounding issue with moving averages

### ISSUE THREAD

**Issue by bassrob** [rabbitmq/rabbitmq-management#35] opened 2015-04-08 10:08 UTC
Hi guys,

I'm sure you're already aware of this (so apologies if I'm the 1,000th person to report this):

![image](https://cloud.githubusercontent.com/assets/10614665/7043108/06829e3a-dddf-11e4-8656-d6de3a3ea847.png)

The weird rounding can affect the Ready, Unacked and Total values.

Cheers,

Rob

**Comment by michaelklishin** [comment] 2015-04-08 10:23
What version do you run?

**Comment by bassrob** [comment] 2015-04-08 10:44
Ah yes, that'd help!  I'm running 3.5.0 with Erlang 17.5.  I can see that you guys have released a bug fix release but I'm not sure which fixes are included.


Cheers Michael,

Rob

**Comment by dumbbell** [comment] 2015-04-08 11:15
We now put the release notes on GitHub, in the `rabbitmq-server` project:
https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_5_1

They are linked from the website as usual.

**Comment by michaelklishin** [comment] 2015-04-08 15:10
@b-hester I'm pretty sure this particular issue wasn't recently fixed. There were *related* things fixed for 3.5.2 but not this one.

Can you tell us a bit about your environment? What does your workload look like? Was there something suspicious in the log files around the time you've noticed this? Were there any stats DB or node failures around that time?

Thank you.

**Comment by bassrob** [comment] 2015-04-21 07:45
Hiya, sorry for the delay, I didn't see the notification.

I haven't been monitoring the DB but can tell you it's running up to ~900mps 24/7.  Further to that, there's not much more I can offer.  It's really nothing serious as we rarely need the Management Console.


Cheers,

Rob

**Comment by Gsantomaggio** [comment] 2015-08-28 18:48
To reproduce the bug you have to:
* Select "Moving average time series" (as the image):

![screen shot 2015-08-28 at 19 11 24](https://cloud.githubusercontent.com/assets/386987/9553901/ffe8ae48-4db9-11e5-963e-7a125bc592f9.png)

* Execute this [gist](https://gist.github.com/Gsantomaggio/e4fcb9db8d4cb605d5d9)

We're going to continue looking at this issue next week.

**Comment by michaelklishin** [comment] 2015-08-28 20:05
@Gsantomaggio good job finding a way to reproduce!

**Comment by Gsantomaggio** [comment] 2015-09-01 10:06
Thank you @michaelklishin 
the problem is that function `fmt_num_thousands` https://github.com/rabbitmq/rabbitmq-management/blob/master/priv/www/js/formatters.js#L211 doesn't accept number with point (like this 1234.5678)

In most cases it works. We are going to fix.

**Comment by michaelklishin** [comment] 2015-09-01 10:11
@Gsantomaggio :+1:

**Comment by dumbbell** [comment] 2015-09-08 08:39
Fixed by #60.

**Closed by dumbbell** 2015-09-08 08:39 UTC
Labels: bug, effort-low
