### ISSUE TITLE
Not authorized responses (401) deliver JSON bodies, skip content-type header

### ISSUE THREAD

**Issue by smee** [rabbitmq/rabbitmq-management#67] opened 2015-10-07 10:02 UTC
If the credentials are invalid the response will encode its body as JSON but does not add the "content-type" header with "application/json" as value. This means that parsing responses needs to be extra careful when interpreting these error messages.

**Comment by michaelklishin** [comment] 2015-10-07 10:17
Thanks, @smee!

@Gsantomaggio assigning to you as you already have some experience with the plugin. This is for `3.5.7` (early November).

**Comment by Gsantomaggio** [comment] 2015-10-09 15:10
The problem is in [this function](https://github.com/rabbitmq/rabbitmq-management/blob/rabbitmq-management-67/src/rabbit_mgmt_util.erl#L288), since the result is `json` but the `content-type` is not set.

we are going to add the  `set_resp_header("Content-Type", "application/json"`

**Comment by michaelklishin** [comment] 2015-10-12 11:22
Fixed in #69.

**Closed by michaelklishin** 2015-10-12 11:22 UTC
Labels: bug, effort-low, usability
