### ISSUE TITLE
Get Message can't deal unicode

### ISSUE THREAD

**Issue by wxj95** [rabbitmq/rabbitmq-management#826] opened 2020-07-01 05:58 UTC
## Please Help Maintainers and Contributors Help You

In order for the RabbitMQ team to investigate your issue, please provide
**as much as possible** of the following details:
  
* RabbitMQ version
RabbitMQ 3.8.4
* Erlang version
Erlang 23.0

Publish message `Mattermost Desktop App <4.4.0` to RabbitMQ

But I Get Message From RabbitMQ is `Mattermost Desktop App \u003c4.4.0`

**Comment by lukebakken** [comment] 2020-07-01 12:35
I'm assuming that "get message from RabbitMQ" is via the management web interface. This is meant as a debugging tool. If you consume the message using AMQP or the HTTP API the message content will be correct.

**Comment by lukebakken** [comment] 2020-07-01 12:35
(@michaelklishin assuming wontfix)

**Closed by lukebakken** 2020-07-01 12:35 UTC

**Comment by michaelklishin** [comment] 2020-07-01 13:28
There is no evidence that the issue is on RabbitMQ side. A traffic capture demo with `rabbitmqadmin` would be considered (RabbitMQ itself treats messages as opaque byte streams) but I'd expect it to be a client issue. I don't know what this "Mattermost Desktop App", or how can we reproduce what it does.

**Comment by michaelklishin** [comment] 2020-07-01 13:30
I cannot reproduce with `3.8.5` and `rabbitmqadmin`:

```
rabbitmqadmin get queue=mirrored.cq.1 ackmode=ack_requeue_true count=30                                                                                                                                                         1 ↵
+---------------+----------+---------------+-------------------------+---------------+------------------+-------------+
|  routing_key  | exchange | message_count |         payload         | payload_bytes | payload_encoding | redelivered |
+---------------+----------+---------------+-------------------------+---------------+------------------+-------------+
| mirrored.cq.1 |          | 19            | Сообщение кириллицей 0  | 41            | string           | True        |
| mirrored.cq.1 |          | 18            | Сообщение кириллицей 1  | 41            | string           | True        |
| mirrored.cq.1 |          | 17            | Сообщение кириллицей 2  | 41            | string           | True        |
| mirrored.cq.1 |          | 16            | Сообщение кириллицей 3  | 41            | string           | True        |
| mirrored.cq.1 |          | 15            | Сообщение кириллицей 4  | 41            | string           | True        |
| mirrored.cq.1 |          | 14            | Сообщение кириллицей 5  | 41            | string           | True        |
| mirrored.cq.1 |          | 13            | Сообщение кириллицей 6  | 41            | string           | True        |
| mirrored.cq.1 |          | 12            | Сообщение кириллицей 7  | 41            | string           | True        |
| mirrored.cq.1 |          | 11            | Сообщение кириллицей 8  | 41            | string           | True        |
| mirrored.cq.1 |          | 10            | Сообщение кириллицей 9  | 41            | string           | True        |
| mirrored.cq.1 |          | 9             | Сообщение кириллицей 10 | 42            | string           | True        |
| mirrored.cq.1 |          | 8             | Сообщение кириллицей 11 | 42            | string           | True        |
| mirrored.cq.1 |          | 7             | Сообщение кириллицей 12 | 42            | string           | True        |
| mirrored.cq.1 |          | 6             | Сообщение кириллицей 13 | 42            | string           | True        |
| mirrored.cq.1 |          | 5             | Сообщение кириллицей 14 | 42            | string           | True        |
| mirrored.cq.1 |          | 4             | Сообщение кириллицей 15 | 42            | string           | True        |
| mirrored.cq.1 |          | 3             | Сообщение кириллицей 16 | 42            | string           | True        |
| mirrored.cq.1 |          | 2             | Сообщение кириллицей 17 | 42            | string           | True        |
| mirrored.cq.1 |          | 1             | Сообщение кириллицей 18 | 42            | string           | True        |
| mirrored.cq.1 |          | 0             | Сообщение кириллицей 19 | 42            | string           | True        |
+---------------+----------+---------------+-------------------------+---------------+------------------+-------------+
```
