### ISSUE TITLE
Importing global runtime parameters via definitions inserts values as Erlang maps instead of proplists

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-management#528] opened 2018-01-02 13:06 UTC
mertz___ on #rabbitmq reports that when he imports the `mqtt_port_to_vhost_mapping` global parameter's definitions for the MQTT plugin through the HTTP API, the plugin fails to get its value with the following exception:

```
{badarg,[
  {lists,keyfind,[<<"1883">>,1,#{<<"1883">> => <<"device">>,<<"1884">> => <<"admin">>}
],[]}
```

He is using RabbitMQ 3.7.2 on Erlang 20.1.7.

Indeed, when the parameter is set from the command line:

```
rabbitmqctl set_global_parameter \
  mqtt_port_to_vhost_mapping  \
  '{"1883":"device", "1884":"admin"}'
```

The value is stored as an Erlang proplist:

```
(rabbit@magellan)2> ets:i(rabbit_runtime_parameters).
<1   > {runtime_parameters,mqtt_port_to_vhost_mapping,
                     ...
EOT  (q)uit (p)Digits (k)ill /Regexp -->p1
{runtime_parameters,mqtt_port_to_vhost_mapping,
                    [{<<"1883">>,<<"device">>},{<<"1884">>,<<"admin">>}]}
```

However, when the same parameter is imported using the web UI with the following input:
```json
{
  "vhosts":[{"name":"device"},{"name":"admin"}],
  "global_parameters":[
    {
      "name":"mqtt_port_to_vhost_mapping",
      "value":{"1883":"device","1884":"admin"}
    }
  ]
}
```

The value is stored as an Erlang map:

```
(rabbit@magellan)1> ets:i(rabbit_runtime_parameters).
                     ...
<2   > {runtime_parameters,mqtt_port_to_vhost_mapping,
                     ...
EOT  (q)uit (p)Digits (k)ill /Regexp -->p2                               
{runtime_parameters,mqtt_port_to_vhost_mapping,
                    #{<<"1883">> => <<"device">>,<<"1884">> => <<"admin">>}}
```

rabbitmqctl(8) calls `rabbit_runtime_parameters:parse_set_global()` parses the JSON input, [converts it to a proplist if it's a map](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_runtime_parameters.erl#L109), then calls `set_global()` to store the result. The management plugin parses the JSON and calls `set_global()` directly, skipping the possible conversion to a proplist.

This explains the inconsistency and thus the crash of the plugin which [expects a proplist](https://github.com/rabbitmq/rabbitmq-mqtt/blob/master/src/rabbit_mqtt_processor.erl#L607).

**Comment by Mert-Z** [comment] 2018-01-02 13:25
The problem is that I need those global parameters configured with the startup of RabbitMQ which is running inside a docker container. Definitions json file was a neat way for me to set this configuration up as part of docker build.
Now as a workaround, it seems like, I now need to deploy a background script that will wait for RabbitMQ startup and then execute rabbitmqctl to set the parameters.
Any other suggestions for a workaround?

**Comment by michaelklishin** [comment] 2018-01-02 13:39
The only workaround there is is to not rely on this obscure feature in the MQTT plugin.

**Comment by michaelklishin** [comment] 2018-01-02 13:41
While we should add the conversion step to the HTTP API handler, the MQTT plugin in 3.7.x should support both proplsits and maps. We won't be using proplists forever now that we require 19.3+.

**Comment by michaelklishin** [comment] 2018-01-02 14:06
The easiest solution here is to make `rabbit_mqtt_processor:get_vhost_from_port_mapping/2` accept both types of values. Runtime parameters can be stored as anything. I will file a new issue for the MQTT plugin.

**Comment by michaelklishin** [comment] 2018-01-02 14:10
Actually it should be easy to special case certain parameters in `add_global_parameter/2`. However, a map value can already stored by an older version, so https://github.com/rabbitmq/rabbitmq-mqtt/issues/156 must be resolved anyway.

**Comment by michaelklishin** [comment] 2018-01-02 17:40
Oh, there's workaround number 3: the good ol' vhost in username convention we have. The plugin will extract vhost from username if you follow this format: `{username}:{vhost}` (unless `ignore_colons_in_username` is set to `true` for the plugin).

**Comment by Mert-Z** [comment] 2018-01-03 07:56
Thanks for the workaround#3 @michaelklishin but unfortunately this workaround does not seem backwards compatible such that I don't have any control on the existing active MQTT producers which are configured to send username in plain format.

Btw, small type in your comment: should be ```{vhost}:{username}``` instead of ```{username}:{vhost}```.

**Comment by michaelklishin** [comment] 2018-01-03 15:28
OK, then in the meantime global parameters have to be set up via `rabbitmqctl`. This was addressed in v3.7.x and will ship in 3.7.3 in a few weeks or so.

**Closed by michaelklishin** 2018-01-03 15:28 UTC
Labels: bug, effort-low

**Comment by dumbbell** [comment] 2018-01-03 15:55
The [latest snapshot](https://dl.bintray.com/rabbitmq/all-dev/rabbitmq-server/3.7.3-alpha.5/rabbitmq-server-generic-unix-3.7.3-alpha.5.tar.xz) contains the patches and looks fine to me.

@Mert-Z: Could you please give it a try?

**Comment by Mert-Z** [comment] 2018-01-08 10:21
@dumbbell: Patch works perfectly. :thumbsup:
`2018-01-08 10:12:11.492 [info] <0.712.0> MQTT vhost picked using MQTT port to vhost mapping`
`2018-01-08 10:12:11.495 [info] <0.712.0> accepting MQTT connection <0.712.0> (192.168.33.1:62410 -> 192.168.33.10:1884)`
`2018-01-08 10:12:56.615 [info] <0.763.0> MQTT vhost picked using MQTT port to vhost mapping`
`2018-01-08 10:12:56.619 [info] <0.763.0> accepting MQTT connection <0.763.0> (192.168.33.1:62415 -> 192.168.33.10:1883)`
