### ISSUE TITLE
unable to grant a user permissions to a custom topic via web ui

### ISSUE THREAD

**Issue by dch** [rabbitmq/rabbitmq-management#812] opened 2020-05-22 22:07 UTC
* RabbitMQ version 3.8.3 + admin plugins from same version
* Erlang version 21.3.8.14

If your issue involves RabbitMQ management UI or HTTP API, please also provide
the following:

 * Browser and its version: Firefox 76
 * What management UI page was used (if applicable)
    http://localhost:15672/#/users/:some_user
 * How the HTTP API requests performed can be reproduced with `curl`
 
- when logged in as admin to the std admin console
- and selecting a user
- it is not possible to add topic permissions to a custom non-default exchange
- only the default `(AMQP default)` and `amq.*` exchanges appear in the UI.

NB  the actual task was to add write permissions to a given topic exchange for a specific vhost, to create a "write-only" user to publish to a routing key similar to `syslog.<hostname>`. On a local rabbitmq system I would probably run:

```
$ rabbitmqctl set_topic_permissions -p vhost rsyslog api.topic "^api.topic" "^$"
```

**Comment by michaelklishin** [comment] 2020-05-22 22:26
I cannot reproduce with `3.8.4-rc.3` but since you have mentioned a "specific vhost", this is likely a duplicate of #806.

**Closed by michaelklishin** 2020-05-22 22:26 UTC

**Comment by dch** [comment] 2020-05-23 13:15
whoops - definitely a duplicate
