### ISSUE TITLE
Make it easier to differentiate between Delete and Purge buttons on the queue page

### ISSUE THREAD

**Issue by dkoen** [rabbitmq/rabbitmq-management#142] opened 2016-03-02 16:21 UTC
We had an issue with permissions where someone meant to purge a queue and accidentally clicked the delete button which caused us some minor problems. Would it be possible to make the difference between the buttons more clear? As it stands it's pretty hard to tell (popup withstanding). 

From previous: https://github.com/rabbitmq/rabbitmq-server/issues/670

**Comment by michaelklishin** [comment] 2016-03-04 00:22
I don't have a suggestion for how the two can be distinguished better — both are destructive operations — and the Delete button has a confirmation.

I really fail to see how #146 would make anything clearer. The real problem here is probably that the Purge button doesn't have a confirmation, even though it's a destructive operation. We could also rename Purge to Purge Messages, at least that would reflect that the queue itself won't be removed.

**Comment by michaelklishin** [comment] 2016-03-04 00:23
@Gsantomaggio do you have an opinion on this?

**Comment by Gsantomaggio** [comment] 2016-03-04 08:20
About the #146 I think that won't help.
In order to be started we would modify also `exchange` section  adding `delete exchange`,  `admin`  section adding `delete user / vhost` etc.

The improvement I see are:

1. Add `Purge` confirmation ( as suggest by @michaelklishin )
2. Change the color in `red` for the delete operations, somethings like `Danger Zone` on github settings.

**Comment by jackar** [comment] 2016-03-04 15:16
@Gsantomaggio we've had multiple independent teams/individuals accidentally delete queues because of the placement of these buttons. See [fitt's law](https://en.wikipedia.org/wiki/Fitts%27s_law) for an HCI theory on distance between logical targets. 

It's one thing to write the front-end layer and know the placement of the buttons and another to be a new user. Delete/purge is unclear. It could mean delete/purge all messages, accounting for their synonymous definitions, which could cause a user to click delete without having gazed to the other side of the screen where the purge button appears. On the other hand, it could also be interpreted in the way that was intended.

Ultimately, this issue revolves around semantics, I'm not sure how helpful coloration will be and confirmation for purge is a solution without a problem.

**Comment by bdshroyer** [comment] 2016-03-14 15:57
Addressed in [PR #142](https://github.com/rabbitmq/rabbitmq-management/pull/147).

**Closed by bdshroyer** 2016-03-14 15:57 UTC
Labels: usability
