### ISSUE TITLE
HTTP API JSON serialization fails on Erlang R16B03

### ISSUE THREAD

**Issue by wes-novack** [rabbitmq/rabbitmq-management#277] opened 2016-08-17 23:38 UTC
I just upgraded to RabbitMQ version 3.6.5 (from 3.6.1) on Ubuntu 14.04 and now the management web UI returns a 500 when accessing the queues page. 

```Got response code 500 with body {"error":"JSON encode error: {bad_term,<0.481.0>}","reason":"While encoding: \n ``` *truncated*

erlang version: 1:16.b.3-dfsg-1ubuntu2.1

This page https://www.rabbitmq.com/which-erlang.html seems to indicate that version R16B03 should be fine for running RabbitMQ 3.6.5 as well as "most plugins".

This is the latest erlang package version available in the Ubuntu 14.04 repos as of now.

**Comment by michaelklishin** [comment] 2016-08-18 04:52
It likely has nothing to do with Erlang version, however, it certainly doesn't happen to me on 18.x or 19.0. How can we reproduce?

**Comment by michaelklishin** [comment] 2016-08-18 11:38
@Gsantomaggio this may or may not be a duplicate of #278 but since they are in the same area, assigning both to you.

**Comment by Gsantomaggio** [comment] 2016-08-18 16:07
@wes-novack I am trying to reproduce the issue, without success. 

I am using `RabbitMQ 3.6.5, Erlang R16B03` updated from `RabbitMQ 3.6.1, Erlang R16B03`.

Do you have the same problem executing:

`curl -X GET -u guest:guest http://localhost:15672/api/queues/{your_vhost}` 
  
  for example

`curl -X GET -u guest:guest http://localhost:15672/api/queues/%2F` ?

Can we have more info to reproduce the issue? 

Thank you.

**Comment by wes-novack** [comment] 2016-08-18 16:08
I just spun up a fresh Ubuntu instance using the same versions and I am not seeing the problem on the new host, therefore, the issue must be within the upgrade process. Started at RabbitMQ version 3.6.1, installed 3.6.5 over the top, then started seeing the issue...

**Comment by dcorbacho** [comment] 2016-08-18 20:17
@wes-novack Where you running two different Rabbit versions in a single cluster during the upgrade?

The parsing of the events changed in 3.6.2, with the parallelisation of the statistics DB collector. A mixed cluster would certainly produce that kind of error.

**Comment by Gsantomaggio** [comment] 2016-08-18 21:08
@dcorbacho good point!! 

Yes, the problem is mixing the versions:

```
Got response code 500 with body {"error":"JSON encode error: {bad_term,<32781.1074.0>}","reason":"While encoding: \n[{total_count,1},\n {item_count,1},\n {filtered_count,1},\n {page,1},\n {page_size,100},\n {page_count,1},\n {items,\n [[{memory,12888},\n {messages,0},\n {messages_details,[{rate,0.0}]},\n {messages_ready,0},\n {messages_ready_details,[{rate,0.0}]},\n {messages_unacknowledged,0},\n {messages_unacknowledged_details,[{rate,0.0}]},\n {idle_since,<<\"2016-08-18 21:04:14\">>},\n {consumer_utilisation,''},\n {policy,''},\n {exclusive_consumer_pid,''},\n {exclusive_consumer_tag,''},\n {consumers,0},\n {slave_pids,''},\n {synchronised_slave_pids,''},\n 
```
Let's wait the @wes-novack feedback and then we can close the issue.

**Comment by wes-novack** [comment] 2016-08-18 21:16
Yes, the other nodes were running 3.6.1.  The docs do still say that running mixed patch versions in a cluster is okay. Ref: [upgrading](https://www.rabbitmq.com/clustering.html#upgrading) 

I also saw issues with an HA policy in the cluster not being applied as configured, which makes me think that it is completely not okay to upgrade a live cluster from 3.6.1 to > 3.6.2. It sounds like 3.6.2 should have been a new minor version if it doesn't follow the standard upgrade behavior.

**Comment by Gsantomaggio** [comment] 2016-08-18 21:41
@wes-novack Thank you. 
Maybe we should mention it on the RabbitMQ  website. 

btw the incompatibility is related only to the management UI, as you can read here:
https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_2 

If you have found another issue related  to the `HA`,  please post it on the [group](https://groups.google.com/forum/#!forum/rabbitmq-users)

**Closed by Gsantomaggio** 2016-08-18 21:41 UTC
Labels: no-decision

**Comment by michaelklishin** [comment] 2016-08-19 05:37
@wes-novack management plugin incompatibility is explicitly called out in effectively the first section of [3.6.2 release notes](https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_2). You can run 3.6.1, 3.6.2 and later versions in a mixed cluster if you don't run management plugin on all of them (which is absolutely not required to collect stats from all nodes).

In case of this plugin, we intentionally decided to introduce a breaking change in 3.6.2 and will do so again in 3.6.6 or 3.6.7 because its current design only goes so far for systems with a large number of collections in queues. This is such as commonly reported issue on rabbitmq-users that we will do it in 3.6.6.

I cannot comment on "issues with an HA policy" because it is not particularly specific. What I can comment on is https://github.com/rabbitmq/rabbitmq-server/issues/812, which is a known bug fixed in laster version and why we highly recommend all 3.6.2 users to upgrade ASAP and earlier version users to SKIP THAT VERSION ENTIRELY.
