### ISSUE TITLE
rabbitmqadmin not importing

### ISSUE THREAD

**Issue by Genacvali** [rabbitmq/rabbitmq-management#729] opened 2019-08-12 10:08 UTC
Hello
Could you pls assist
I'm trying to write bash script for backuping the definitions of RabbitMQ for customer. I am using the rabbitmqadmin. Export works fine, but when I'm trying to import the rabbitmqadmin import only one user without any permissions and thats all.

Here are the logs output:
```
2019-08-12 04:15:39.528 [info] <0.5006.0> Asked to import definitions. Acting user: admin
2019-08-12 04:15:39.540 [info] <0.5006.0> Importing users...
2019-08-12 04:15:39.540 [info] <0.5006.0> Creating user 'solution'
```

thats all.

RabbitMQ 3.7.16 Erlang 22.0.7
CentOS Linux release 7.6.1810
3 node cluster

Thank you

**Comment by michaelklishin** [comment] 2019-08-12 10:11
This almost certainly is a duplicate of #715. Please [upgrade](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.7.17).

**Closed by michaelklishin** 2019-08-12 10:11 UTC

**Comment by Genacvali** [comment] 2019-08-12 10:16
You mean to upgrade the RabbitMQ up to 3.7.17? Are there any other solutions?

**Comment by michaelklishin** [comment] 2019-08-12 10:22
Yes, I mean upgrade to `3.7.17`.

**Comment by Genacvali** [comment] 2019-08-12 10:22
Is there any ways to perform the upgrade without downtime?

**Comment by michaelklishin** [comment] 2019-08-12 10:45
Please consult the [doc guide on upgrades](https://www.rabbitmq.com/upgrade.html). A cluster of `3.7.16` nodes can be upgraded to `3.7.17` in a rolling fashion. A single node must be stopped for upgrade.
